### ISSUE TITLE
Conda version isn't working

### ISSUE THREAD

**Issue by gorgW** [amd/openmm-hip#19]
When I build the plugin, it works fine and hip platform is there,
while when I use Conda in creating the environment using this line 
conda create -n openmm-env -c streamhpc -c conda-forge --strict-channel-priority openmm-hip
 and I run the test 
python -m openmm.testInstallation
HIP platform is not there. 

any idea what might cause this  ?

**Comment by ex-rzr** [comment]
README contains a command to check why the HIP platform is not loaded. What does it print?

**Comment by gorgW** [comment]
---Loaded---
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMPME.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMCPU.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMOpenCL.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMRPMDOpenCL.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMDrudeOpenCL.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMAmoebaOpenCL.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMRPMDReference.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMDrudeReference.so
/opt/conda/envs/openmm-env/lib/plugins/libOpenMMAmoebaReference.so
---Failed---
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMHIP.so: libhipfft.so.0: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMRPMDHIP.so: libhipfft.so.0: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMDrudeHIP.so: libhipfft.so.0: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMRPMDCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMDrudeCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMAmoebaHIP.so: libhipfft.so.0: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMAmoebaCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory
Error loading library /opt/conda/envs/openmm-env/lib/plugins/libOpenMMHipCompiler.so: libamdhip64.so.6: cannot open shared object file: No such file or directory

**Comment by ex-rzr** [comment]
Install hipfft, see README.

What ROCm version do you have, btw?
If the old 5.* then you might need to install `openmm-hip==8.0.0`, if the newer 6.* then `openmm-hip==8.1.1beta` should work (for this version you don't need to install hipfft).

**Comment by gorgW** [comment]
This is helpful. 
Thanks.
